
import javax.swing.DefaultListModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Fadhil Yaafi W
 */
public class Gui2 extends javax.swing.JFrame {
    DefaultListModel<String> dlm;

    /**
     * Creates new form GuiSimpel
     */
    public Gui2() {
        initComponents();        
        // Inisialisasi DefaultListModel baru
        this.dlm = new DefaultListModel<>();
        // Menghubungkan model dlm ke komponen jListItem kamu
        this.List_Item.setModel(dlm);
    }
    
    // Method buatan untuk menambahkan item ke model list
    private void addItem(String namaItem) {
        dlm.addElement(namaItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        List_Item = new javax.swing.JList<>();
        Tombol_Insert_Data = new javax.swing.JButton();
        Teks_Nama_Item = new javax.swing.JTextField();
        Label_Nama_Item = new javax.swing.JLabel();
        Tombol_Add = new javax.swing.JButton();
        Tombol_Update = new javax.swing.JButton();
        Tombol_Delete = new javax.swing.JButton();
        Tombol_Clear_All = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        List_Item.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(List_Item);

        Tombol_Insert_Data.setText("Insert Data");
        Tombol_Insert_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tombol_Insert_DataActionPerformed(evt);
            }
        });

        Teks_Nama_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Teks_Nama_ItemActionPerformed(evt);
            }
        });

        Label_Nama_Item.setText("Nama Item :");

        Tombol_Add.setText("Add");
        Tombol_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tombol_AddActionPerformed(evt);
            }
        });

        Tombol_Update.setText("Update");
        Tombol_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tombol_UpdateActionPerformed(evt);
            }
        });

        Tombol_Delete.setText("Delete");
        Tombol_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tombol_DeleteActionPerformed(evt);
            }
        });

        Tombol_Clear_All.setText("Clear All");
        Tombol_Clear_All.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tombol_Clear_AllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Tombol_Insert_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_Nama_Item)
                        .addGap(18, 18, 18)
                        .addComponent(Teks_Nama_Item))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Tombol_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Tombol_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Tombol_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Tombol_Clear_All, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Tombol_Insert_Data)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_Nama_Item)
                            .addComponent(Teks_Nama_Item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Tombol_Add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Tombol_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tombol_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tombol_Clear_All, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tombol_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tombol_AddActionPerformed
        // TODO add your handling code here:
        addItem(Teks_Nama_Item.getText());
        Teks_Nama_Item.setText("");
    }//GEN-LAST:event_Tombol_AddActionPerformed

    private void Tombol_Insert_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tombol_Insert_DataActionPerformed
        // TODO add your handling code here:
        String[] items = {"buku", "meja", "kursi", "tas", "pintu"};
        for (String item : items) {
            dlm.addElement(item);
        }
    }//GEN-LAST:event_Tombol_Insert_DataActionPerformed

    private void Tombol_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tombol_UpdateActionPerformed
        // TODO add your handling code here:
        int index = List_Item.getSelectedIndex();
        String selected = Teks_Nama_Item.getText();
        dlm.setElementAt(selected, index);
        
        // Mengosongkan kembali kotak input teks
        Teks_Nama_Item.setText("");
    }//GEN-LAST:event_Tombol_UpdateActionPerformed

    private void Tombol_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tombol_DeleteActionPerformed
        // TODO add your handling code here:
        // Mencari baris data ke berapa yang sedang diklik di list
        int index = List_Item.getSelectedIndex();
        // Menghapus item pada baris tersebut dari list
        dlm.removeElementAt(index);
        
        // Mengosongkan kembali kotak input teks
        Teks_Nama_Item.setText("");
    }//GEN-LAST:event_Tombol_DeleteActionPerformed

    private void Tombol_Clear_AllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tombol_Clear_AllActionPerformed
        // TODO add your handling code here:
        dlm.clear();
    }//GEN-LAST:event_Tombol_Clear_AllActionPerformed

    private void Teks_Nama_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Teks_Nama_ItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Teks_Nama_ItemActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Gui2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Nama_Item;
    private javax.swing.JList<String> List_Item;
    private javax.swing.JTextField Teks_Nama_Item;
    private javax.swing.JButton Tombol_Add;
    private javax.swing.JButton Tombol_Clear_All;
    private javax.swing.JButton Tombol_Delete;
    private javax.swing.JButton Tombol_Insert_Data;
    private javax.swing.JButton Tombol_Update;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}