import javax.swing.DefaultListModel;
import java.util.ArrayList;
import java.util.List;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Fadhil Yaafi W
 */
public class Gui3 extends javax.swing.JFrame {
    DefaultListModel<String> dlm;
    List<String> items = new ArrayList<>();
    String[] datas = {"buku", "meja", "kursi", "tas", "pintu"};
    
    /**
     * Creates new form Gui3
     */
    public Gui3() {
        initComponents();
        dlm = new DefaultListModel<>();
        list_item.setModel(dlm);

        for (String data : datas) {
            dlm. addElement (data);
            updateJumDataTersimpan () ;
        }
    } 
        
    private void updateJumDataTersimpan () {
        data_tersimpan. setText (
        "Data tersimpan = " + items.size () ) ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tombol_insert = new javax.swing.JButton();
        tombol_savedata = new javax.swing.JButton();
        data_tersimpan = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_item = new javax.swing.JList<>();
        label_nama_item = new javax.swing.JLabel();
        teks_nama_item = new javax.swing.JTextField();
        tombol_add = new javax.swing.JButton();
        tombol_update = new javax.swing.JButton();
        tombol_delete = new javax.swing.JButton();
        tombol_clearall = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tombol_insert.setText("Insert Data");
        tombol_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_insertActionPerformed(evt);
            }
        });

        tombol_savedata.setText("Save Data");
        tombol_savedata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_savedataActionPerformed(evt);
            }
        });

        data_tersimpan.setText("Data Tersimpan = ");

        list_item.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(list_item);

        label_nama_item.setText("Item Name :");

        teks_nama_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teks_nama_itemActionPerformed(evt);
            }
        });

        tombol_add.setText("Add");
        tombol_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_addActionPerformed(evt);
            }
        });

        tombol_update.setText("Update");
        tombol_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_updateActionPerformed(evt);
            }
        });

        tombol_delete.setText("Delete");
        tombol_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_deleteActionPerformed(evt);
            }
        });

        tombol_clearall.setText("Clear All");
        tombol_clearall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_clearallActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tombol_insert, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(tombol_savedata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_nama_item, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tombol_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tombol_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teks_nama_item)
                    .addComponent(data_tersimpan, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(tombol_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tombol_clearall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tombol_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(data_tersimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombol_savedata, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_nama_item, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teks_nama_item, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tombol_add, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tombol_update, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tombol_clearall, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tombol_delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teks_nama_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teks_nama_itemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teks_nama_itemActionPerformed

    private void tombol_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_addActionPerformed
        // TODO add your handling code here:
        String namaItem = teks_nama_item.getText().trim();
    
        if (!namaItem.isEmpty()) {
            dlm.addElement(namaItem); // Langsung masukkan ke model
            teks_nama_item.setText(""); // Kosongkan textfield
        }
    }//GEN-LAST:event_tombol_addActionPerformed

    private void tombol_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_insertActionPerformed
        // TODO add your handling code here:
        for (String item : items) {
            dlm.addElement (item);
        }
    }//GEN-LAST:event_tombol_insertActionPerformed

    private void tombol_clearallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_clearallActionPerformed
        // TODO add your handling code here:
        dlm.clear();
    }//GEN-LAST:event_tombol_clearallActionPerformed

    private void tombol_savedataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_savedataActionPerformed
        // TODO add your handling code here:
        if (!items.isEmpty()) {
            items.clear();
        }
        
        for (int i = 0; i < dlm.getSize(); i++) {
            items.add(dlm.getElementAt (i));
        }

        updateJumDataTersimpan () ;
    }//GEN-LAST:event_tombol_savedataActionPerformed

    private void tombol_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_updateActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        int index = list_item.getSelectedIndex();
        String selected = teks_nama_item.getText();
        dlm.setElementAt(selected, index);
        
        // Mengosongkan kembali kotak input teks
        teks_nama_item.setText("");
    }//GEN-LAST:event_tombol_updateActionPerformed

    private void tombol_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_deleteActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        // Mencari baris data ke berapa yang sedang diklik di list
        int index = list_item.getSelectedIndex();
        // Menghapus item pada baris tersebut dari list
        dlm.removeElementAt(index);
        
        // Mengosongkan kembali kotak input teks
        teks_nama_item.setText("");
    }//GEN-LAST:event_tombol_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(Gui3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel data_tersimpan;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_nama_item;
    private javax.swing.JList<String> list_item;
    private javax.swing.JTextField teks_nama_item;
    private javax.swing.JButton tombol_add;
    private javax.swing.JButton tombol_clearall;
    private javax.swing.JButton tombol_delete;
    private javax.swing.JButton tombol_insert;
    private javax.swing.JButton tombol_savedata;
    private javax.swing.JButton tombol_update;
    // End of variables declaration//GEN-END:variables
}