import javax.swing.DefaultListModel;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Set;
import java.util.Map;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Fadhil Yaafi W
 */
public class Gui4 extends javax.swing.JFrame {
    DefaultListModel<String> dlm;
    java.util.List<String> itemList = new java.util.ArrayList<>();
    java.util.Set<String> itemSet = new java.util.HashSet<>();
    java.util.Map<Integer, String> itemMap = new java.util.HashMap<>();

    /**
     * Creates new form Gui4
     */
    public Gui4() {
        initComponents();
        dlm = new DefaultListModel<>();
        list_item.setModel(dlm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list_item = new javax.swing.JList<>();
        teks_nama_item = new javax.swing.JTextField();
        tombol_savetolist = new javax.swing.JButton();
        tombol_insertdatalist = new javax.swing.JButton();
        tombol_savetoset = new javax.swing.JButton();
        tombol_insertdataset = new javax.swing.JButton();
        tombol_savetomap = new javax.swing.JButton();
        tombol_insertdatamap = new javax.swing.JButton();
        label_nama_item = new javax.swing.JLabel();
        tombol_clearall = new javax.swing.JButton();
        tombol_add = new javax.swing.JButton();
        tombol_update = new javax.swing.JButton();
        tombol_delete = new javax.swing.JButton();
        data_tersimpan_list = new javax.swing.JLabel();
        data_tersimpan_set = new javax.swing.JLabel();
        data_tersimpan_map = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        list_item.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list_item);

        tombol_savetolist.setText("Save to List ->");
        tombol_savetolist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_savetolistActionPerformed(evt);
            }
        });

        tombol_insertdatalist.setText("<- Insert Data List");
        tombol_insertdatalist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_insertdatalistActionPerformed(evt);
            }
        });

        tombol_savetoset.setText("Save to Set ->");
        tombol_savetoset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_savetosetActionPerformed(evt);
            }
        });

        tombol_insertdataset.setText("<- Insert Data Set");
        tombol_insertdataset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_insertdatasetActionPerformed(evt);
            }
        });

        tombol_savetomap.setText("Save to Map ->");
        tombol_savetomap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_savetomapActionPerformed(evt);
            }
        });

        tombol_insertdatamap.setText("<- Insert Data Map");
        tombol_insertdatamap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_insertdatamapActionPerformed(evt);
            }
        });

        label_nama_item.setText("Item Name :");

        tombol_clearall.setText("Clear All");
        tombol_clearall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_clearallActionPerformed(evt);
            }
        });

        tombol_add.setText("Add");
        tombol_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_addActionPerformed(evt);
            }
        });

        tombol_update.setText("Update");
        tombol_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_updateActionPerformed(evt);
            }
        });

        tombol_delete.setText("Delete");
        tombol_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_deleteActionPerformed(evt);
            }
        });

        data_tersimpan_list.setText("Data Tersimpan = ");

        data_tersimpan_set.setText("Data Tersimpan = ");

        data_tersimpan_map.setText("Data Tersimpan = ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(tombol_clearall, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_nama_item, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(teks_nama_item)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tombol_savetolist, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tombol_insertdatalist, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tombol_savetoset, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tombol_insertdataset, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tombol_savetomap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tombol_insertdatamap, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(data_tersimpan_list, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(data_tersimpan_set, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(data_tersimpan_map))
                        .addGap(56, 56, 56))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tombol_add, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tombol_update, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tombol_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tombol_savetolist, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(data_tersimpan_list, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombol_insertdatalist, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(data_tersimpan_set, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tombol_savetoset, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombol_insertdataset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(data_tersimpan_map, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tombol_savetomap, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombol_insertdatamap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_nama_item, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teks_nama_item, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombol_clearall, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombol_add, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombol_update, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombol_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombol_savetolistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_savetolistActionPerformed
        // TODO add your handling code here:
        itemList.clear();
        
        for (int i = 0; i < dlm.getSize(); i++) {
            itemList.add(dlm.getElementAt(i));
        }
        
        data_tersimpan_list.setText("Data Tersimpan = " + itemList.size());
    }//GEN-LAST:event_tombol_savetolistActionPerformed

    private void tombol_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_updateActionPerformed
        // TODO add your handling code here:
        int index = list_item.getSelectedIndex();
        String selected = teks_nama_item.getText().trim();
    
        if (index != -1 && !selected.isEmpty()) {
            dlm.setElementAt(selected, index);
            teks_nama_item.setText("");
        }
    }//GEN-LAST:event_tombol_updateActionPerformed

    private void tombol_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_addActionPerformed
        // TODO add your handling code here:
        String namaItem = teks_nama_item.getText().trim();
    
        if (!namaItem.isEmpty()) {
            dlm.addElement(namaItem); // Langsung masukkan ke model
            teks_nama_item.setText(""); // Kosongkan textfield
        }
    }//GEN-LAST:event_tombol_addActionPerformed

    private void tombol_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_deleteActionPerformed
        // TODO add your handling code here:
        int index = list_item.getSelectedIndex();
    
        if (index != -1) {
            dlm.removeElementAt(index);
            teks_nama_item.setText("");
        }
    }//GEN-LAST:event_tombol_deleteActionPerformed

    private void tombol_clearallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_clearallActionPerformed
        // TODO add your handling code here:
        dlm.clear();
    }//GEN-LAST:event_tombol_clearallActionPerformed

    private void tombol_insertdatalistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_insertdatalistActionPerformed
        // TODO add your handling code here:
        dlm.clear(); // Bersihkan JList terlebih dahulu
        
        for (String item : itemList) {
            dlm.addElement(item);
        }
    }//GEN-LAST:event_tombol_insertdatalistActionPerformed

    private void tombol_savetosetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_savetosetActionPerformed
        // TODO add your handling code here:
        itemSet.clear();
        
        for (int i = 0; i < dlm.getSize(); i++) {
            itemSet.add(dlm.getElementAt(i));
        }
        
        data_tersimpan_set.setText("Data Tersimpan = " + itemSet.size());
    }//GEN-LAST:event_tombol_savetosetActionPerformed

    private void tombol_insertdatasetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_insertdatasetActionPerformed
        // TODO add your handling code here:
        dlm.clear();
        
        for (String item : itemSet) {
            dlm.addElement(item);
        }
    }//GEN-LAST:event_tombol_insertdatasetActionPerformed

    private void tombol_savetomapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_savetomapActionPerformed
        // TODO add your handling code here:
        itemMap.clear(); // Bersihkan data lama
    
        for (int i = 0; i < dlm.getSize(); i++) {
            itemMap.put(i, dlm.getElementAt(i)); // i sebagai key, nama item sebagai value
        }
    
        data_tersimpan_map.setText("Data Tersimpan = " + itemMap.size());
    }//GEN-LAST:event_tombol_savetomapActionPerformed

    private void tombol_insertdatamapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_insertdatamapActionPerformed
        // TODO add your handling code here:
        dlm.clear();
    
        for (java.util.Map.Entry<Integer, String> entry : itemMap.entrySet()) {
            dlm.addElement(entry.getValue());
        }
    }//GEN-LAST:event_tombol_insertdatamapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel data_tersimpan_list;
    private javax.swing.JLabel data_tersimpan_map;
    private javax.swing.JLabel data_tersimpan_set;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_nama_item;
    private javax.swing.JList<String> list_item;
    private javax.swing.JTextField teks_nama_item;
    private javax.swing.JButton tombol_add;
    private javax.swing.JButton tombol_clearall;
    private javax.swing.JButton tombol_delete;
    private javax.swing.JButton tombol_insertdatalist;
    private javax.swing.JButton tombol_insertdatamap;
    private javax.swing.JButton tombol_insertdataset;
    private javax.swing.JButton tombol_savetolist;
    private javax.swing.JButton tombol_savetomap;
    private javax.swing.JButton tombol_savetoset;
    private javax.swing.JButton tombol_update;
    // End of variables declaration//GEN-END:variables
}